"""Constants for RAG retrieval configuration."""


DEFAULT_PREFETCH_DENSE = 50
DEFAULT_PREFETCH_SPARSE = 50


FUSION_METHOD = "rrf"
DEFAULT_RERANK_CANDIDATES = 100

DEFAULT_TOP_K = 10

FILTER_KEY_QUERY_TYPE = "query_type"

CODE_TYPE_DIAGNOSIS = "diagnosis"
CODE_TYPE_PROCEDURE = "procedure"

DEFAULT_DENSE_VECTOR_NAME = "dense"
DEFAULT_SPARSE_VECTOR_NAME = "sparse_bm25"
